version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: floksbox-backend
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn floksbox_backend.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    working_dir: /app
    volumes:
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=floksbox_backend.settings
      - DJANGO_DEBUG=0
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: floksbox-frontend
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: floksbox-net


