version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: floksbox-backend
    command: ["/app/docker-entrypoint.sh"]
    working_dir: /app
    volumes:
      - backend_db_data:/data
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=floksbox_backend.settings
      - DJANGO_DEBUG=0
      - DJANGO_SQLITE_NAME=/data/db.sqlite3
      - DJANGO_SECURE_SSL_REDIRECT=0
      - DJANGO_SESSION_COOKIE_SECURE=0
      - DJANGO_CSRF_COOKIE_SECURE=0
      - DJANGO_ALLOWED_HOSTS=91.229.8.43,backend,localhost,127.0.0.1
      - DJANGO_CSRF_TRUSTED_ORIGINS=http://91.229.8.43:8000,http://91.229.8.43,https://91.229.8.43
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: floksbox-frontend
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: floksbox-net

volumes:
  backend_db_data:
