version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: floksbox-backend
    command: [ "/app/docker-entrypoint.sh" ]
    working_dir: /app
    volumes:
      - backend_db_data:/data
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/media:/app/media
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: floksbox-frontend
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: floksbox-net

volumes:
  backend_db_data:
