# Generated by Django 5.2.4 on 2025-08-01 09:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import requests_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название категории', max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о категории', null=True, verbose_name='Описание категории')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, help_text='Отображается ли категория на сайте', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название товара для отображения на сайте', max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(help_text='Подробное описание товара (до 200 слов)', validators=[requests_app.models.validate_word_count], verbose_name='Описание')),
                ('image', models.ImageField(help_text='Изображение товара (JPG, PNG, WebP, до 5MB)', upload_to=requests_app.models.product_image_path, validators=[requests_app.models.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Изображение')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена в рублях (опционально)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цена за штуку')),
                ('height', models.DecimalField(decimal_places=2, help_text='Высота товара в сантиметрах', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(9999.99)], verbose_name='Высота (см)')),
                ('width', models.DecimalField(decimal_places=2, help_text='Ширина товара в сантиметрах', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(9999.99)], verbose_name='Ширина (см)')),
                ('depth', models.DecimalField(decimal_places=2, help_text='Глубина товара в сантиметрах', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(9999.99)], verbose_name='Глубина (см)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, help_text='Отображается ли товар на сайте', verbose_name='Активен')),
                ('category', models.ForeignKey(blank=True, help_text='Категория товара', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='requests_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='requests_ap_categor_e604dc_idx'), models.Index(fields=['created_at'], name='requests_ap_created_fbbf19_idx')],
            },
        ),
    ]
